# -*- coding: utf-8 -*-
"""BayesianNetwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJze2ArXyp6z73RDaLkNjpow_Epuhn3E
"""

#Dataset Creation
import numpy as np

age = np.random.choice(['Young', 'Middle', 'Old'], size=100)
gen = np.random.choice(['Male', 'Female'], size = 100)
chol = np.random.choice(['High', 'Normal'], size = 100)
hd = np.random.choice(['Yes', 'No'], size = 100)

import pandas as pd
dataset = pd.DataFrame({'Age': age, 'Gender': gen, 'Cholesterol' : chol, 'HeartDisease' : hd})

dataset

!pip install pgmpy

#Constructing Bayesian Network
import pandas as pd
from pgmpy.models import BayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

model = BayesianNetwork([
    ('Age', 'HeartDisease'),
    ('Gender', 'HeartDisease'),
    ('Cholesterol', 'HeartDisease')
])
model.fit(dataset, estimator=MaximumLikelihoodEstimator)
inference = VariableElimination(model)

q1 = inference.query(variables=['HeartDisease'],
                    evidence={'Age': 'Middle', 'Gender': 'Male', 'Cholesterol': 'High'})
q2 = inference.query(variables=['HeartDisease'],
                    evidence={'Age': 'Middle', 'Gender': 'Female', 'Cholesterol': 'Normal'})
print("Age: Middle, Gender: Male, Cholesterol: High")
print(q1)

print("\n\nAge: Middle, Gender: Female, Cholesterol: Normal")
print(q2)

import networkx as nx

model = BayesianNetwork([
    ('Age', 'Gender'),
    ('Gender', 'HeartDisease'),
    ('Cholesterol', 'HeartDisease')
])

G = nx.DiGraph()
G.add_nodes_from(model.nodes())
G.add_edges_from(model.edges())

nx.draw_networkx(G, with_labels=True)

