# -*- coding: utf-8 -*-
"""BayesianNetwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJze2ArXyp6z73RDaLkNjpow_Epuhn3E
"""

import pandas as pd

data = pd.DataFrame({
    'Age': ['young', 'young', 'young', 'young', 'young', 'middle', 'middle', 'middle', 'middle', 'old', 'old', 'old', 'old', 'old'],
    'Gender': ['male', 'male', 'female', 'female', 'female', 'male', 'male', 'female', 'female', 'male', 'male', 'male', 'female', 'female'],
    'Cholesterol': ['high', 'high', 'high', 'normal', 'normal', 'high', 'normal', 'normal', 'normal', 'high', 'normal', 'normal', 'normal', 'high'],
    'HeartDisease': ['yes', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
})

data.to_csv('heart_disease_data.csv', index=False)

data = pd.read_csv('heart_disease_data.csv')

print(data.head())

!pip install pgmpy

#Constructing Bayesian Network
import pandas as pd
from pgmpy.models import BayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

model = BayesianNetwork([
    ('Age', 'HeartDisease'),
    ('Gender', 'HeartDisease'),
    ('Cholesterol', 'HeartDisease')
])
model.fit(data, estimator=MaximumLikelihoodEstimator)
inference = VariableElimination(model)

query_result = inference.query(variables=['HeartDisease'],
                    evidence={'Age': 'middle', 'Gender': 'male', 'Cholesterol': 'high'})
print(query_result)
query_result = inference.query(variables=['HeartDisease'],
                    evidence={'Age': 'middle', 'Gender': 'female', 'Cholesterol': 'normal'})
print(query_result)

import networkx as nx
import matplotlib.pyplot as plt
model = BayesianNetwork([
    ('Age', 'Gender'),
    ('Gender', 'HeartDisease'),
    ('Cholesterol', 'HeartDisease')
])

G = nx.DiGraph()
G.add_nodes_from(model.nodes())
G.add_edges_from(model.edges())

pos=nx.spring_layout(G)
plt.figure(figsize=(10,10))
nx.draw(G, with_labels=True, node_size=4000,node_color='lightblue', font_size=16,font_color="black",font_weight="bold",arrowsize=20)
plt.title("Bayesian Network Structure for Heart Disease Diagnosis")
plt.show()

